### ISSUE TITLE
Greenkeeper is shutting down

### ISSUE THREAD

**Issue by corymharper** [sparksuite/react-accessible-dropdown-menu-hook#102]
As Greenkeeper has mentioned in recent pull requests, and on it's website (https://greenkeeper.io/), it is shutting down, in favor of a more advanced solution with a bigger team behind it. The new solution goes a bit beyond the scope of this repository, but we would still like to have automated package updates.

**Comment by corymharper** [comment]
The solution that I am currently looking at replacing Greenkeeper with is Dependabot, a solution that was acquired and is being / has been integrated into Github. I'll use this issue to post relevant information and open a pull request when necessary.

**Comment by corymharper** [comment]
The first question that came to mind with regards to Dependabot was, "Will it work with a frozen lockfile?" As that was a significant difficulty with we face with Greenkeeper and our continuous integration solution, Travis-CI. According to [this discussion](https://github.com/dependabot/feedback/issues/227), it does work and has tests internally to ensure that it does.

**Comment by corymharper** [comment]
We will need a `config.yml` file in a `.dependabot/` directory at the root of our project. A basic configuration looks something like this:

```
version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
```

You can add on as many update configs as you want, simply separated by `-package_manager`, which works well for us since we have a monolithic repo.

**Comment by corymharper** [comment]
They have some options we may be interested in, such as `default_assignees`, `default_reviewers`, and `default_labels`.

I believe a basic config for our project would look something like:

```
version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependabot"
  - package_manager: "javascript"
    directory: "/demo"
    update_schedule: "live"
    default_labels:
      - "dependabot"
```

It detects whether you use `yarn` or `npm` as your package manager out of the box.
